#!/usr/bin/env python
"""Generate a steps.csv for a 3-electrode voltage scan (Grid x Anode x Cathode matrix), loadable
straight into run_steps.py. No hardware access at all -- this only writes a text file.

Anode is swept as an OFFSET above Grid, and Cathode as an OFFSET above Anode (not raw volts), so a
step's actual voltages are Grid=g, Anode=g+a, Cathode=g+a+c as g/a/c each sweep their own range.
Every point in the matrix is checked against the same electrode ordering rule run_steps.py enforces
before anything is written, and the file is round-tripped through run_steps.py's own CSV parser as a
self-check before being saved.

Exit codes: 0 written | 1 bad arguments | 2 a generated step breaks the electrode rule | 3 refused to
overwrite an existing file (pass --force)
"""
import argparse
import sys
from pathlib import Path

from backend.scan_csv import generate_scan_steps, scan_csv_text, self_check, inclusive_range
from run_steps import parse_channel_map


def build_parser():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("out_csv", help="path to write, e.g. scan_steps.csv")
    p.add_argument("--channel-map", required=True, type=parse_channel_map,
                   help="REQUIRED, exactly Grid/Anode/Cathode, e.g. Grid=0,Anode=4,Cathode=5")
    g = p.add_argument_group("Grid (V)")
    g.add_argument("--grid-min", type=float, required=True)
    g.add_argument("--grid-max", type=float, required=True)
    g.add_argument("--grid-step", type=float, required=True)
    a = p.add_argument_group("Anode offset above Grid (V): Anode = Grid + offset")
    a.add_argument("--anode-offset-min", type=float, required=True)
    a.add_argument("--anode-offset-max", type=float, required=True)
    a.add_argument("--anode-offset-step", type=float, required=True)
    c = p.add_argument_group("Cathode offset above Anode (V): Cathode = Anode + offset")
    c.add_argument("--cathode-offset-min", type=float, required=True)
    c.add_argument("--cathode-offset-max", type=float, required=True)
    c.add_argument("--cathode-offset-step", type=float, required=True)
    p.add_argument("--hold-s", type=float, required=True, help="data-acquisition hold time at every point, in seconds")
    p.add_argument("--min-delta", type=float, default=20.0,
                   help="Anode/Cathode must be at least this far above Grid (V); same default as run_steps.py")
    p.add_argument("--daq", choices=["Y", "N", "none"], default="Y",
                   help="trailing DAQ column for every row (default Y: acquire at every scan point). "
                        "'none' omits the column, so each step follows the run's own --daq-cmd default")
    p.add_argument("--force", action="store_true", help="overwrite out_csv if it already exists")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)
    if set(args.channel_map) != {"Grid", "Anode", "Cathode"}:
        print(f"Cannot generate:\n  - --channel-map must name exactly Grid, Anode and Cathode, "
              f"got {sorted(args.channel_map)}", file=sys.stderr)
        return 1

    try:
        steps = generate_scan_steps(
            grid_min=args.grid_min, grid_max=args.grid_max, grid_step=args.grid_step,
            anode_offset_min=args.anode_offset_min, anode_offset_max=args.anode_offset_max,
            anode_offset_step=args.anode_offset_step,
            cathode_offset_min=args.cathode_offset_min, cathode_offset_max=args.cathode_offset_max,
            cathode_offset_step=args.cathode_offset_step,
            hold_s=args.hold_s, min_delta=args.min_delta)
    except ValueError as e:
        print(f"Cannot generate:\n  - {e}", file=sys.stderr)
        return 2

    daq = None if args.daq == "none" else args.daq
    comment = (
        f"Generated by generate_scan_csv.py: Grid {args.grid_min:g}-{args.grid_max:g} step {args.grid_step:g} V; "
        f"Anode offset {args.anode_offset_min:g}-{args.anode_offset_max:g} step {args.anode_offset_step:g} V; "
        f"Cathode offset {args.cathode_offset_min:g}-{args.cathode_offset_max:g} step {args.cathode_offset_step:g} V\n"
        f"hold {args.hold_s:g} s/step, min-delta {args.min_delta:g} V, channel map "
        + ", ".join(f"{n}=Ch{c}" for n, c in sorted(args.channel_map.items(), key=lambda kv: kv[1])) + "\n"
        "Row format: ch,V,ch,V,...,hold_s[,DAQ Y/N] -- see run_steps.py --help"
    )
    text = scan_csv_text(steps, args.channel_map, daq=daq, comment=comment)

    problems = self_check(text, args.channel_map, args.min_delta)
    if problems:
        print("Cannot generate: the generated file failed its own self-check (this is a bug, please report it):\n"
              + "\n".join(f"  - {p}" for p in problems), file=sys.stderr)
        return 2

    out = Path(args.out_csv)
    if out.exists() and not args.force:
        print(f"Cannot generate:\n  - {out} already exists (pass --force to overwrite)", file=sys.stderr)
        return 3
    out.write_text(text)

    total_h = len(steps) * args.hold_s / 3600.0
    n_grid = len(inclusive_range(args.grid_min, args.grid_max, args.grid_step, "grid"))
    n_anode = len(inclusive_range(args.anode_offset_min, args.anode_offset_max, args.anode_offset_step, "anode offset"))
    n_cathode = len(inclusive_range(args.cathode_offset_min, args.cathode_offset_max, args.cathode_offset_step,
                                    "cathode offset"))
    print(f"Wrote {len(steps)} steps ({n_grid} x {n_anode} x {n_cathode} Grid x Anode-offset x Cathode-offset) to {out}")
    print(f"Total hold time alone: {total_h:.2f} h (excludes ramp time between points -- see run_steps.py --dry-run "
          "for a full, ramp-accounted estimate)")
    print(f"First step: Grid={steps[0].grid:g} Anode={steps[0].anode:g} Cathode={steps[0].cathode:g}")
    print(f"Last step:  Grid={steps[-1].grid:g} Anode={steps[-1].anode:g} Cathode={steps[-1].cathode:g}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
